
spring.application.name=FootyFocus4


# spring.datasource.url=${SPRING_DATASOURCE_URL}
# spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
# spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
# spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=${SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_LOB_NON_CONTEXTUAL_CREATION}
# spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}


leagueStandings.api.url=${LEAGUE_STANDINGS_API_URL}
detailedPlayer.api.url=${DETAILED_PLAYER_API_URL}
topScorer.api.url=${TOP_SCORER_API_URL}
compWinners.api.url=${COMP_WINNERS_API_URL}
fixtures.api.url=${FIXTURES_API_URL}
player.search.api.url=${PLAYER_SEARCH_API_URL}
football.api.key=${FOOTBALL_API_KEY}