spring.application.name=FootyFocus4

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.hibernate.ddl-auto= update

leagueStandings.api.url = https://api.football-data.org/v4/competitions/{leagueCode}/standings?season={season}
detailedPlayer.api.url = https://api.football-data.org/v4/persons/
topScorer.api.url=https://api.football-data.org/v4/competitions/{leagueCode}/scorers?season={season}
compWinners.api.url = https://api.football-data.org/v4/competitions/
fixtures.api.url=https://api.football-data.org/v4/teams/
player.search.api.url=https://www.thesportsdb.com/api/v1/json/3/searchplayers.php
football.api.key=e277c182b1374e1e96a27d065fab02a5